<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
    <ApplicationIcon>Assets\phishellstudio.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhigrosShellGUI\PhigrosShellGUI.csproj" />
    <ProjectReference Include="..\..\PhigrosArchive\PhigrosArchive.csproj" />
  </ItemGroup>
</Project>
